# Configuration file for Nettskjema importer

questions:

  - udf:        'Method used to purify DNA/RNA'
    line:       'Method used to purify DNA / RNA'

  - udf:        'Method used to determine concentration'
    line:       'Method used to determine concentration'

  - udf:        'Sample buffer'
    line:       'Buffer in which samples dissolved'

  - udf:        'Species'
    line:       'Species'

  - udf:        'Reference genome'
    line:       'Reference genome and release version'
    default:    '-- Not provided --'
  
  - udf:        'Project Goal'
    line:       'Project Goal'
  
  - udf:        'Project type'
    line:       'Project type'
    mapping:    'project_type'
  
  - udf:        'REK approval number'
    line:       'REK approval number'
  
  - udf:        'Funded by Norsk Forskningsradet'
    line:       'Is project fully or partly funded by The Research Council of Norway (NFR)?'
    mapping:    'yes_no_bool'

  - udf:        'Evaluation type'
    line:       'Are the samples ready to sequence'
    mapping:    'evaluation_type'

  - udf:        'Library prep used'
    line:       'If yes, please state which kit / method you used'

  - udf:        'Sample prep requested'
    default:    'None'

  - udf:        'Sample prep requested'
    line:       'For DNA samples'
    mapping:    sample_prep_dna
    
  - udf:        'Sample prep requested'
    line:       'For RNA samples'
    mapping:    sample_prep_rna

  - udf:        'Sample prep requested'
    line:       'Do you need rRNA depletion (HMR)?'
    mapping:    sample_prep_depletion

  - udf:        'Sequencing instrument requested'
    line:       'Sequencing Instrument requested'

# "Choose run type" for MiSeq & NextSeq sets lengths, PE mode and sequencer detail
  - udf:        'Sequencing instrument requested'
    line:       'Choose run type'
    mapping:    'choose_run_type_sequencer'
  - udf:        'Read length requested'
    line:       'Choose run type'
    mapping:    'choose_run_type_readlength'
  - udf:        'Sequencing method'
    line:       'Choose run type'
    mapping:    'choose_run_type_seqmeth'

# NovaSeq
  - udf:        'Sequencing instrument requested'
    line:       'Choose Flowcell'
    mapping:    'novaseq_fc'
  - udf:        'Read length requested'
    line:       'Choose read length'
    mapping:    choose_read_length_readlength
  - udf:        'Sequencing method'
    line:       'Choose read length'
    mapping:    choose_read_length_seqmeth

  - udf:        'Total # of lanes requested'
    line:       'Total number of runs requested'

  - udf:        'Delivery method'
    line:       'Data delivery'
    mapping:    'delivery_method'
    
  - udf:        'Delivery method'
    line:       'Data delivery'
    mapping:    'delivery_method'
    
  - udf:        'Delivery method'
    line:       'Select hard drive'
    mapping:    'delivery_method2_hdd'

  - udf:        'NeLS project identifier'
    line:       'Existing NeLS project ID'

  - udf:        'TSD project ID'
    line:       'TSD project ID (e.g. pXX)'

  - udf:        'Bioinformatic services'
    line:       'Do you want to use our bioinformatic analysis service?'
    mapping:    'yes_no_bool'

  - udf:        'Contact person'
    line:       'Contact Name'

  - udf:        'Contact email'
    line:       'Contact Email'

  - udf:        'Contact telephone'
    line:       'Contact Telephone'

  - udf:        'Contact institution'
    line:       'Contact Institution'

  - udf:        'Billing contact person'
    line:       'Billing contact person'

  - udf:        'Billing email'
    line:       'Billing Email'

  - udf:        'Billing telephone'
    line:       'Billing Telephone'

  - udf:        'Billing institution'
    line:       'Billing institution and full billing address'
    transform:  'first_line'

  - udf:        'Billing address'
    line:       'Billing institution and full billing address'
    default:    '-- Not provided --'

  - udf:        'Purchase order number'
    line:       'Purchase Order Number'

  - udf:        'Kontostreng (Internal orders only)'
    line:       'Kontostreng (Koststed-Prosjekt-Kilde)'

#  Not importing this information into LIMS
#  - udf:        'TODO'
#    line:       'Institution VAT number'

  - udf:        'Sample type'
    default:    '-- Not provided --'

  - udf:        'Prepaid account'
    default:    'No'

  - udf:        'Date samples received'
    transform:  'todays_date'
    default:    'placeholder'

mappings:
  delivery_method:
    - in: (non-sensitive data) Upload to our password protected delivery server.
      out: Norstore
    - in: (non-sensitive data) Upload to NeLS
      out: NeLS project
    - in: (sensitive data) Upload to TSD project
      out: TSD project
    - in: (sensitive data) Portable hard drive
      out: HDD_PLACEHOLDER_STRING

  delivery_method2_hdd:
    - in: Your own portable hard drive
      out: User HDD
    - in: Purchase a portable hard drive
      out: New HDD

  evaluation_type:
    - in: 'Yes'
      out: QC only
    - in: 'No'
      out: Prep
  
  novaseq_fc:
    - in: SP
      out: NovaSeq SP
    - in: S1
      out: NovaSeq S1
    - in: S2
      out: NovaSeq S2
    - in: S4
      out: NovaSeq S4
    - in: 1.5B
      out: NovaSeq X 1.5B
    - in: 25B
      out: NovaSeq X 25B
    - in: 10B
      out: NovaSeq X 10B

  
  project_type:
    - in: Non-sensitive
      out: Non-Sensitive
    - in: Sensitive
      out: Sensitive
  
  yes_no_bool:
    - in: 'Yes'
      out: True
    - in: 'No'
      out: False

  sample_prep_dna:
    - in: 'Illumina DNA Prep, Tagmentation'
      out: 'Illumina DNA Prep'
    - in: 'TruSeq® Nano DNA library prep'
      out: 'TruSeq Nano'
    - in: 'ThruPLEX® low-input sample prep'
      out: 'ThruPLEX'
    - in: '16S prep (Fadrosh DW et. al)'
      out: '16S prep'
    - in: "I'm unsure, please advise"
      out: 'User unsure'

  sample_prep_rna:
    - in: 'Strand-specific mRNA-seq library prep'
      out: 'TruSeq Stranded mRNA'
    - in: 'Strand-specific total RNA-seq library prep'
      out: 'DUMMY_SEE_DEPLETION_QUESTION'
    - in: 'small RNA library prep'
      out: 'QiaSeq miRNA'
    - in: 'rRNA/globin depletion'
      out: 'rRNA/Globin Depletion'
    - in: "I'm unsure, please advise"
      out: 'User unsure'

  sample_prep_depletion:
    - in: 'Yes'
      out: 'TruSeq Stranded total RNA + FastSelect rRNA/Globin Depletion'
    # Is this too much of a hack? The question about depletion is only asked for the totalRNA prep
    - in: 'No'
      out: 'TruSeq Stranded total RNA'

  choose_read_length_readlength:
    - in: '1 x 100 bp'
      out: '100'
    - in: '2 x 50 bp'
      out: '50'
    - in: '2 x 100 bp'
      out: '100'
    - in: '2 x 150 bp'
      out: '150'
    - in: '2 x 250 bp'
      out: '250'

  choose_read_length_seqmeth:
    - in: '1 x 100 bp'
      out: 'Single Read'
    - in: '2 x 50 bp'
      out: 'Paired End Read'
    - in: '2 x 100 bp'
      out: 'Paired End Read'
    - in: '2 x 150 bp'
      out: 'Paired End Read'
    - in: '2 x 250 bp'
      out: 'Paired End Read'

  choose_run_type_sequencer:
    - in: '2 x 150 bp Nano v2'
      out: 'MiSeq v2 Nano'
    - in: '2 x 250 bp Nano v2'
      out: 'MiSeq v2 Nano'
    - in: '2 x 150 bp Micro v2'
      out: 'MiSeq v2 Micro'
    - in: '1 x 50 bp v2'
      out: 'MiSeq v2'
    - in: '2 x 25 bp v2'
      out: 'MiSeq v2'
    - in: '2 x 150 bp v2'
      out: 'MiSeq v2'
    - in: '2 x 250 bp v2'
      out: 'MiSeq v2'
    - in: '2 x 75 bp v3'
      out: 'MiSeq v3'
    - in: '2 x 300 bp v3'
      out: 'MiSeq v3'
    - in: '1 x 75 bp High-output'
      out: 'NextSeq high output'
    - in: '2 x 75 bp High-output'
      out: 'NextSeq high output'
    - in: '2 x 150 bp High-output'
      out: 'NextSeq high output'
    - in: '2 x 75 bp Mid-output'
      out: 'NextSeq mid output'
    - in: '2 x 150 bp Mid-output'
      out: 'NextSeq mid output'

  choose_run_type_readlength:
    - in: '2 x 150 bp Nano v2'
      out: '150'
    - in: '2 x 250 bp Nano v2'
      out: '250'
    - in: '2 x 150 bp Micro v2'
      out: '150'
    - in: '1 x 50 bp v2'
      out: '50'
    - in: '2 x 25 bp v2'
      out: '25'
    - in: '2 x 150 bp v2'
      out: '150'
    - in: '2 x 250 bp v2'
      out: '250'
    - in: '2 x 75 bp v3'
      out: '75'
    - in: '2 x 300 bp v3'
      out: '300'
    - in: '1 x 75 bp High-output'
      out: '75'
    - in: '2 x 75 bp High-output'
      out: '75'
    - in: '2 x 150 bp High-output'
      out: '150'
    - in: '2 x 75 bp Mid-output'
      out: '75'
    - in: '2 x 150 bp Mid-output'
      out: '150'

  choose_run_type_seqmeth:
    - in: '2 x 150 bp Nano v2'
      out: 'Paired End Read'
    - in: '2 x 250 bp Nano v2'
      out: 'Paired End Read'
    - in: '2 x 150 bp Micro v2'
      out: 'Paired End Read'
    - in: '1 x 50 bp v2'
      out: 'Single Read'
    - in: '2 x 25 bp v2'
      out: 'Paired End Read'
    - in: '2 x 150 bp v2'
      out: 'Paired End Read'
    - in: '2 x 250 bp v2'
      out: 'Paired End Read'
    - in: '2 x 75 bp v3'
      out: 'Paired End Read'
    - in: '2 x 300 bp v3'
      out: 'Paired End Read'
    - in: '1 x 75 bp High-output'
      out: 'Single Read'
    - in: '2 x 75 bp High-output'
      out: 'Paired End Read'
    - in: '2 x 150 bp High-output'
      out: 'Paired End Read'
    - in: '2 x 75 bp Mid-output'
      out: 'Paired End Read'
    - in: '2 x 150 bp Mid-output'
      out: 'Paired End Read'
      
