project_fields:
  "Project type": "FHI-Covid19"
  "Evaluation type": "Prep"
  "Contact email": "covidseq@fhi.no"
  "Contact person":  "FHI"
  "Contact institution": "FHI"
  "Delivery method": "FHI-Covid19"

sample_fields: 

workflow: "Covid Swift SNAP"

tasks:
  - "ReadFHIv2SampleFile"
  - "CheckExistingProjects"
  - "CreateProject"
  - "UploadFile"
  - "CreatePlateAndSamples"
  - "AssignWorkflow"

project_name_placeholder: "FHIx-Sx"
add_file_basename_to_project_name: true
